# Generated by Django 2.1.5 on 2019-06-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(default='', max_length=1600)),
                ('updateTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '要做的事',
                'verbose_name_plural': '要做的事',
                'db_table': 'toDoList',
            },
        ),
    ]
